spring.application.name=online-bookstore
# Increase the number of allowed files/parts in one request
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-parameter-count=100
spring.servlet.multipart.file-size-threshold=0
server.tomcat.max-part-count=30
